#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory
# Source version OpenFoam
source /opt/openfoam9/etc/bashrc

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application directory
application=$(getApplication)

runApplication blockMesh
runApplication topoSet
runApplication refineHexMesh c0 -overwrite

runApplication decomposePar -cellDist
runParallel $application

#------------------------------------------------------------------------------
